[build]
  command = "npm run build"
  publish = "client/build"  # Update this when you have a frontend build

[functions]
  directory = "netlify/functions"

# Redirect API requests to your serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
